sudo: false
language: ruby
addons:
  apt:
    packages:
    - fontforge
    - eot-utils
    - unzip
before_script:
  - wget http://people.mozilla.com/~jkew/woff/woff-code-latest.zip
  - unzip woff-code-latest.zip -d sfnt2woff
  - cd sfnt2woff && make
  - export PATH=$PATH:$PWD/sfnt2woff
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.3
  - 2.2.2
  - ruby-head
